-- Managed mode: explanations generated by the web app rather than with a key
-- the reader had to obtain and paste into a file on the device.
--
-- The point of these tests is that the credential arrives through pairing and
-- nothing else changes: no file is written, no key is stored, and a reader who
-- already has their own key is never quietly switched off it.
local here = debug.getinfo(1, "S").source:sub(2):match("^(.*)[/\\][^/\\]*$") or "."
local ko = dofile(here .. "/support.lua")
local check = ko.check

local MANAGED_URL = "https://lunote.xyz/api/v1/ai/chat"

-- The shared stub ships a configured key, which would outrank managed mode. Most
-- of these tests are about the case where the reader has configured nothing.
local function withoutLocalKey()
    ko.modules["lunote_config"].api_key = nil
end

local function withLocalKey()
    ko.modules["lunote_config"].api_key = "sk-reader-own-key"
end

local function pairManaged(mode)
    local Sync = require("lunote_sync")
    ko.http.response = {
        token = "device-token-xyz",
        ai = mode and { mode = "managed", url = MANAGED_URL } or { mode = "byok" },
    }
    return Sync.pair("ABC123")
end

print("pairing carries the AI configuration")
ko.reset()
withoutLocalKey()
do
    local Sync = require("lunote_sync")
    check("no managed url before pairing", Sync.getManagedUrl() == nil)

    local ok, err = pairManaged(true)
    check("pairing succeeds", ok == true, err)
    check("the token is stored", Sync.getToken() == "device-token-xyz")
    -- The whole of the paid setup: six characters in, credential and routing out.
    check("managed url is remembered", Sync.getManagedUrl() == MANAGED_URL,
        tostring(Sync.getManagedUrl()))
end

print("\na free account is told to use its own key")
ko.reset()
withoutLocalKey()
do
    local Sync = require("lunote_sync")
    pairManaged(false)
    check("pairing still works", Sync.isConfigured() == true)
    check("no managed url", Sync.getManagedUrl() == nil)
end

print("\nexplanations are routed to the web app")
ko.reset()
withoutLocalKey()
do
    local Sync = require("lunote_sync")
    pairManaged(true)

    local queryModel = require("lunote_query")
    ko.http.response = {
        model = "google/gemini-2.5-flash-lite",
        choices = { { message = { role = "assistant", content = "Because Kant said so." } } },
    }
    local answer, err, model = queryModel({ { role = "user", content = "explain this" } })

    check("an answer comes back", answer == "Because Kant said so.", err)
    check("it went to the web app, not the provider", ko.http.url == MANAGED_URL,
        tostring(ko.http.url))
    -- The pairing token is the credential. No provider key exists on the device.
    check("the pairing token is the credential",
        ko.http.headers["Authorization"] == "Bearer device-token-xyz",
        tostring(ko.http.headers["Authorization"]))
    -- Letting the device pick would let a paired reader ask for the priciest
    -- model on the platform, billed to us.
    check("no model is requested", ko.http.sent[#ko.http.sent].model == nil)
    check("the model that answered is recorded", model == "google/gemini-2.5-flash-lite")
end

print("\na key the reader configured always wins")
ko.reset()
withLocalKey()
do
    local Sync = require("lunote_sync")
    pairManaged(true)
    check("managed mode is still on offer", Sync.getManagedUrl() == MANAGED_URL)

    local queryModel = require("lunote_query")
    ko.http.response = {
        choices = { { message = { role = "assistant", content = "answered" } } },
    }
    queryModel({ { role = "user", content = "explain this" } })

    check("the request goes to the provider",
        ko.http.url == "https://openrouter.ai/api/v1/chat/completions", tostring(ko.http.url))
    check("with the reader's own key",
        ko.http.headers["Authorization"] == "Bearer sk-reader-own-key",
        tostring(ko.http.headers["Authorization"]))
end

print("\na custom endpoint also wins")
ko.reset()
withoutLocalKey()
do
    -- Someone pointing the plugin at a local Ollama, as the README documents,
    -- has said what they want clearly enough; a subscription must not override
    -- it and start sending their passages over the internet.
    ko.modules["lunote_config"].api_key = "ollama"
    ko.modules["lunote_config"].base_url = "http://192.168.1.87:11434/v1/chat/completions"
    local Sync = require("lunote_sync")
    pairManaged(true)

    local queryModel = require("lunote_query")
    ko.http.response = {
        choices = { { message = { role = "assistant", content = "local answer" } } },
    }
    local answer = queryModel({ { role = "user", content = "explain this" } })
    check("the local model answers", answer == "local answer")
    check("the local endpoint is used",
        ko.http.url == "http://192.168.1.87:11434/v1/chat/completions", tostring(ko.http.url))
    check("over plain HTTP", ko.http.transport == "http", tostring(ko.http.transport))
    ko.modules["lunote_config"].base_url = nil
end

print("\nsync keeps the configuration current")
ko.reset()
withoutLocalKey()
do
    local History = require("lunote_history")
    local Sync = require("lunote_sync")
    pairManaged(false)
    check("starts on its own key", Sync.getManagedUrl() == nil)

    -- Someone subscribes a week after pairing. Sync is the only channel the
    -- server has to tell the device so.
    History.startConversation{
        book = { uuid = "b1", title = "Critique", authors = "Kant" },
        kind = "explain", highlight = "h", model = "m",
        messages = { { role = "user", content = "q" }, { role = "assistant", content = "a" } },
    }
    ko.http.response = { accepted = 1, ai = { mode = "managed", url = MANAGED_URL } }
    Sync.run{}
    check("sync switches managed mode on", Sync.getManagedUrl() == MANAGED_URL,
        tostring(Sync.getManagedUrl()))

    -- ...and when the plan lapses, back again.
    History.startConversation{
        book = { uuid = "b1", title = "Critique", authors = "Kant" },
        kind = "explain", highlight = "h2", model = "m",
        messages = { { role = "user", content = "q" }, { role = "assistant", content = "a" } },
    }
    ko.http.response = { accepted = 1, ai = { mode = "byok" } }
    Sync.run{}
    check("sync switches managed mode off again", Sync.getManagedUrl() == nil)
end

print("\nunpairing gives the device back its own key")
ko.reset()
withoutLocalKey()
do
    local Sync = require("lunote_sync")
    pairManaged(true)
    Sync.unpair()
    -- The token was the credential for generation too, so leaving managed mode
    -- on would point the device at an endpoint it can no longer authenticate to.
    check("managed mode is cleared", Sync.getManagedUrl() == nil)

    local queryModel = require("lunote_query")
    local answer, err = queryModel({ { role = "user", content = "explain this" } })
    check("and the reader is told what to do", answer == nil and err ~= nil)
    check("the message mentions both routes",
        err:find("pair this device", 1, true) ~= nil
            and err:find("OPENROUTER_API_KEY", 1, true) ~= nil, err)
end

print("\na malformed ai block is ignored rather than trusted")
ko.reset()
withoutLocalKey()
do
    local Sync = require("lunote_sync")
    ko.http.response = { token = "t", ai = { mode = "managed" } }
    Sync.pair("ABC123")
    check("managed mode needs a url", Sync.getManagedUrl() == nil)

    ko.http.response = { token = "t", ai = "nonsense" }
    Sync.pair("ABC123")
    check("a non-table ai block is ignored", Sync.getManagedUrl() == nil)
end

ko.summary()
